language: ruby
rvm:
  - 2.0.0
env:
  - DB=postgresql
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database threeSentences_test;' -U postgres
  - bin/rake db:create db:migrate

script: bundle exec rspec spec